[project]
name = "anomer-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiosmtplib>=4.0.2",
    "bcrypt>=5.0.0",
    "beanie>=2.0.1",
    "databases>=0.9.0",
    "fastapi>=0.124.4",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "orjson>=3.11.5",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.12.5",
    "pyjwt[crypto]>=2.10.1",
    "pymongo>=4.16.0",
    "redis>=7.0.1",
    "uvicorn>=0.38.0",
]

[tool.pyright]
# Список папок для анализа
include = ["src"]
# Исключение папок
exclude = ["**/__pycache__", ".venv"]
# Версия Python для проверки совместимости
pythonVersion = "3.13"
# Режим проверки типов: "off", "basic" или "strict"
typeCheckingMode = "strict"
# Отключаю правила
reportInvalidTypeForm = false
reportUnknownVariableType = false